name: Download Videos with yt-dlp (releases)

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
      QUALITY:
        description: 'QUALITY'
        required: true
        default: 'bestvideo*+bestaudio/best'
        type: choice
        options:
          - bestvideo*+bestaudio/best
          - bestvideo[height<=1080]+bestaudio/best[height<=1080]
          - bestvideo[height<=720]+bestaudio/best[height<=720]
          - bestvideo[height<=480]+bestaudio/best[height<=480]
          - bestvideo[height<=360]+bestaudio/best[height<=360]
          - bestvideo[height<=240]+bestaudio/best[height<=240]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Install yt-dlp
        run: |
          aria2c https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp --dir ~/.local/bin -o yt-dlp
          chmod a+rx ~/.local/bin/yt-dlp

      - name: Install deno
        run: |
          curl -fsSL https://deno.land/install.sh | sh
          ln -s ~/.deno/bin/deno ~/.local/bin/deno

      - name: Install ffmpeg
        run: sudo apt update && sudo apt install -yq ffmpeg

      - name: Download Video
        run: |
          mkdir -p ~/Documents/yt-dlp
          echo "${{ secrets.COOKIES }}" | base64 -d > ~/Documents/yt-dlp/cookies.txt
          yt-dlp --format "${{ github.event.inputs.QUALITY }}" -o "%(title)s.%(ext)s" --embed-thumbnail --embed-metadata --embed-subs --sub-langs en --convert-thumbnails jpg --force-overwrites --remux-video mkv --sponsorblock-remove default --cookies ~/Documents/yt-dlp/cookies.txt "${{ github.event.inputs.URL }}"

      - name: Get Downloaded Filename
        id: filename
        run: echo "filename=$(ls -t | head -1)" >> $GITHUB_OUTPUT

      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: ${{ steps.filename.outputs.filename }}
