name: Download Videos with yt-dlp

on:
  workflow_dispatch:
    inputs:
      URL:
        description: 'URL'
        required: true
      QUALITY:
        description: 'QUALITY'
        required: true
        default: 'bestvideo*+bestaudio/best'
        type: choice
        options:
          - bestvideo*+bestaudio/best
          - bestvideo[height<=1080]+bestaudio/best[height<=1080]
          - bestvideo[height<=720]+bestaudio/best[height<=720]
          - bestvideo[height<=480]+bestaudio/best[height<=480]
          - bestvideo[height<=360]+bestaudio/best[height<=360]
          - bestvideo[height<=240]+bestaudio/best[height<=240]

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: downloads

      - name: Install yt-dlp
        run: |
          aria2c https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp --dir ~/.local/bin -o yt-dlp
          chmod a+rx ~/.local/bin/yt-dlp

      - name: Install deno
        run: |
          curl -fsSL https://deno.land/install.sh | sh
          ln -s ~/.deno/bin/deno ~/.local/bin/deno

      - name: Install ffmpeg
        run: sudo apt update && sudo apt install -yq ffmpeg

      - name: Configure Git
        run: |
          git config --global user.email "parsastdev@duck.com"
          git config --global user.name "Parsast"

      - name: Download Video
        run: |
          mkdir -p ~/Documents/yt-dlp
          echo "${{ secrets.COOKIES }}" | base64 -d > ~/Documents/yt-dlp/cookies.txt
          yt-dlp --format "${{ github.event.inputs.QUALITY }}" --embed-thumbnail --embed-metadata --embed-subs --sub-langs en --convert-thumbnails jpg --force-overwrites --remux-video mkv --sponsorblock-remove default --cookies ~/Documents/yt-dlp/cookies.txt "${{ github.event.inputs.URL }}"

      - name: Push Downloaded Video to Repo
        run: |
          git add -A
          git commit -m "push downloaded video to repo"
          git push -u origin downloads
